config/routes.rb
Rails.application.routes.draw do

  resources :group_categories
  resources :group_catgories
  get 'password_resets/new'

  get 'index/index'

  resources :testimonials
  resources :product_categories
  get 'about' => 'pages#about'

  get 'contact' => 'pages#contact'

  get '/home-demo-2' => 'index#home2'
  get '/home-demo-3' => 'index#home3'

  #get 'pages/404'

  get 'login', to: 'sessions#new', as: 'login'

  resources :categories

  resources :sessions

  get '/login' => 'sessions#new'

  resources :users

  resources :password_resets

  get '/register' => 'users#new'

  get 'register/confirm/:id' => 'users#show'

  resources :posts do
    resources :comments
  end

  get '/blog' => 'posts#index'

  get 'tags/:tag', to: 'posts#tag', as: :tag

  resources :products do
    resources :reviews
  end

  get '/shop' => 'products#index'

  root "index#index"

  mount Ckeditor::Engine => '/ckeditor'

  # error pages
  #get "*any", to: "errors#not_found", :via => all
  #match "/500", :to => "errors#internal_server_error", :via => :all

  namespace :qsadmin do

    resources :posts

    resources :dashboards

    get '', to: 'dashboards#index', as: '/'
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
	attr_accessible :name, :content, :status, :user_id, :category_id, :image , :tag_list
	belongs_to :user
	belongs_to :category
	has_many :comments

	has_attached_file :image
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

 	#  	def to_param
	# 	"#{id}-#{name}"
	# end

	has_many :taggings
	has_many :tags, through: :taggings

	def self.tagged_with(name)
	  Tag.find_by_name!(name).posts
	end

	def self.tag_counts
	  Tag.select("tags.*, count(taggings.tag_id) as count").
	    joins(:taggings).group("taggings.tag_id")
	end

	def tag_list
	  tags.map(&:name).join(", ")
	end

	def tag_list=(names)
	  self.tags = names.split(",").map do |n|
	    Tag.where(name: n.strip).first_or_create!
	  end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  #before_action :authorize, except: [:show, :index]

  layout 'layouts/post'

  def index
    @categories = Category.all
    if params[:category].blank?
        @posts = Post.all.order("created_at DESC").limit(6).paginate(:page => params[:page], :per_page => 10)
    else
      @category_id = Category.find_by(name: params[:category]).id   
      @posts = Post.where(:category_id => @category_id).order("created_at DESC").limit(6).paginate(:page => params[:page], :per_page => 10)
    end 
  end

  def tag
    if params[:tag]
        @posts = Post.tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 10)
    end   
  end

  def show
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def new
    #@post = Post.new
    @post = current_user.posts.build
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def create
    @post = current_user.posts.build( post_params )
    @post.category_id = params[:category_id]

    if @post.save
      redirect_to posts_path, notice: 'Post was successfully created.' 
    else
      render 'new' 
    end
  end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def update
      @post.category_id = params[:category_id]
      if @post.update(post_params)
        redirect_to @post, notice: 'Post was successfully updated.' 
      else
        render :edit 
      end
  end

  def destroy
    @post.destroy
      redirect_to posts_path, notice: 'Post was successfully destroyed.' 
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit( :name, :content, :status, :user_id, :category_id, :image, :tag_list )
    end

    def authorize
      if current_user.nil?
        redirect_to login_url, alert: "Not authorized! Please log in."
      else
        if @post && @post.user != current_user
          redirect_to root_path, alert: "Not authorized! Only #{@post.user} has access to this post."
        end
      end
    end
end

app/controllers/qsadmin/posts_controller.rb
class Qsadmin::PostsController < Qsadmin::BaseController
  before_action :set_qsadmin_post, only: [:show, :edit, :update, :destroy]
  

  def index
    @posts = Qsadmin::Post.all.paginate(:page => params[:page], :per_page => 5)
  end

  def show
  end

  def new
    @qsadmin_post = Qsadmin::Post.new
  end

  def edit
  end

  def create
    @qsadmin_post = Qsadmin::Post.new(qsadmin_post_params)

    respond_to do |format|
      if @qsadmin_post.save
        format.html { redirect_to @qsadmin_post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @qsadmin_post }
      else
        format.html { render :new }
        format.json { render json: @qsadmin_post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @qsadmin_post.update(qsadmin_post_params)
        format.html { redirect_to @qsadmin_post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @qsadmin_post }
      else
        format.html { render :edit }
        format.json { render json: @qsadmin_post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @qsadmin_post.destroy
    respond_to do |format|
      format.html { redirect_to qsadmin_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_qsadmin_post
      @qsadmin_post = Post.find(params[:id])
    end

    def qsadmin_post_params
      params.require(:qsadmin_post).permit( :name, :content, :status, :user_id, :category_id, :image, :tag_list )
    end
end

app/helpers/posts_helper.rb
module PostsHelper
	def tag_links(tags)
	  tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ") 
	end
	
	def tag_cloud(tags, classes)
	  max = tags.sort_by(&:count).last
	  tags.each do |tag|
	    index = tag.count.to_f / max.count * (classes.size-1)
	    yield(tag, classes[index.round])
	  end
	end
end

app/helpers/qsadmin/posts_helper.rb
module Qsadmin::PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <p><%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %></p>
    <p><label>Thumbnail </label><%= f.file_field :image %></p>
    <p><label>Name</label><br><%= f.text_field :name %></p>
    <p><label>Content</label><br><%= f.cktext_area :content %></p>
    <p><label>Tags</label><br><%= f.text_field :tag_list %></p>
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="">
	<div class="edit-book-form">
		<h1>Edit Book</h1>
		<%= form_for @post, :html => { :multipart => true } do |f| %>
			<%= f.select :category_id, @categories %>
			<%= f.file_field :image %>
			<%= f.text_field :name, label: "Name" %>
			<%= f.cktext_area :content %>
			<p><label>Tags</label><br><%= f.text_field :tag_list %></p>
			<%= f.button :submit, :class => "btn-custom2" %>
		<% end %>
	</div>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="posts-index">
  <% @categories.each do | cat | %>
    <h2 class="category-name"><%= link_to cat.name, cat %></h2>
    <% cat.posts.order('created_at DESC').limit(6).each do |post| %>
      <div class="col-md-4 post-detail">
        <%= image_tag post.image.url %>
        <h3><%= link_to post.name.first(30), post %></h3>
        <p><label>By </label> <%= link_to post.user.username, user_path(post.user.id) %> | 
          <label>Category:</label> <%= link_to post.category.name, category_path(post.category.id) %></p>
        <p><label>Pushlished at </label> <%= time_ago_in_words(post.created_at) %></p>
        <p>
          Tags: <%= raw post.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %>
        </p>

        <% if session[:user_name] == 'hklong' %>
          <%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>

    <% end %>
  <% end %>
  <div class="clearfix"></div>

  <% if session[:user_id] %>
    <p class="post-button clearfix"><%= link_to 'New Post', new_post_path %></p>
  <% end %>

  <p><%= will_paginate %></p>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="post-index">
	<p id="notice"><%= notice %></p>
	<h3><%= @post.name %></h3>
	<p><label>Author </label> <%= link_to @post.user.username, user_path(@post.user.id) %></p>
	<p><label>Pushlished at </label> <%= time_ago_in_words(@post.created_at) %></p>
	<p><%= raw @post.content %></p>
	<p><label>In : </label><%= link_to @post.category.name, category_path(@post.category.id) %></p>
	<% if current_user && @post.user == current_user %>
		<%= link_to 'Edit', edit_post_path(@post) %>
	<% end %>
	<% if session[:user_name] == 'hklong' %>
	  <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Are you sure ?" } %>
	<% end %>

	<div class="comments">
		<%= render @post.comments %>
		<%= render 'comments/form'  %>
	</div>
</div>

app/views/posts/tag.html.erb
<div class="posts-tags">
  <% @posts.each do |post| %>
  		<div class="col-md-4 tag-img">
  			<%= image_tag post.image.url %>
  		</div>
     	<div class="col-md-8 tag-content">
	        <h3><%= link_to post.name.first(30), post %></h3>
	        <p><label>By </label> <%= link_to post.user.username, user_path(post.user.id) %> | 
	          <label>Category:</label> <%= link_to post.category.name, category_path(post.category.id) %></p>
	        <p><label>Pushlished at </label> <%= time_ago_in_words(post.created_at) %></p>
	        <p>
	          Tags: <%= raw post.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %>
	        </p>
	    </div>
  <% end %>

  <p><%= will_paginate %></p>
</div>