config/routes.rb
Rails.application.routes.draw do

  resources :group_categories
  resources :group_catgories
  get 'password_resets/new'

  get 'index/index'

  resources :testimonials
  resources :product_categories
  get 'about' => 'pages#about'

  get 'contact' => 'pages#contact'

  get '/home-demo-2' => 'index#home2'
  get '/home-demo-3' => 'index#home3'

  #get 'pages/404'

  get 'login', to: 'sessions#new', as: 'login'

  resources :categories

  resources :sessions

  get '/login' => 'sessions#new'

  resources :users

  resources :password_resets

  get '/register' => 'users#new'

  get 'register/confirm/:id' => 'users#show'

  resources :posts do
    resources :comments
  end

  get '/blog' => 'posts#index'

  get 'tags/:tag', to: 'posts#tag', as: :tag

  resources :products do
    resources :reviews
  end

  get '/shop' => 'products#index'

  root "index#index"

  mount Ckeditor::Engine => '/ckeditor'

  # error pages
  #get "*any", to: "errors#not_found", :via => all
  #match "/500", :to => "errors#internal_server_error", :via => :all

  namespace :qsadmin do

    resources :posts

    resources :dashboards

    get '', to: 'dashboards#index', as: '/'
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/group_category.rb
class GroupCategory < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	attr_accessible :name, :content, :status, :user_id, :category_id, :image , :tag_list
	belongs_to :user
	belongs_to :category
	has_many :comments

	has_attached_file :image
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

 	#  	def to_param
	# 	"#{id}-#{name}"
	# end

	has_many :taggings
	has_many :tags, through: :taggings

	def self.tagged_with(name)
	  Tag.find_by_name!(name).posts
	end

	def self.tag_counts
	  Tag.select("tags.*, count(taggings.tag_id) as count").
	    joins(:taggings).group("taggings.tag_id")
	end

	def tag_list
	  tags.map(&:name).join(", ")
	end

	def tag_list=(names)
	  self.tags = names.split(",").map do |n|
	    Tag.where(name: n.strip).first_or_create!
	  end
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :product_category
	has_many :reviews
	belongs_to :users
	has_attached_file :product_image
	validates_attachment_content_type :product_image, content_type: /\Aimage\/.*\Z/

	def self.search(search)
	  if search
	    where("name like ?", "%#{search}%") 
	  else
	    all
	  end
	end


end

app/models/qsadmin.rb
module Qsadmin
  def self.table_name_prefix
    'qsadmin_'
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :product
	belongs_to :user
end

app/models/session.rb
class Session < ActiveRecord::Base
	before_create :encrypt_password
	def encrypt_password
      if password.present?
        self.salt = BCrypt::Engine.generate_salt
        self.password= BCrypt::Engine.hash_secret(password, salt)
      end
    end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	attr_accessible :name
	has_many :taggings
	has_many :posts, through: :taggings

	def self.counts
	  self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
	end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
	has_attached_file :image
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
    #attr_accessor :password
    #has_secure_password
	  has_many :posts, dependent: :destroy
    has_many :reviews
    has_many :comments
    before_save :encrypt_password
    after_save :clear_password
    before_create { generate_token(:auth_token) }

    has_attached_file :avatar
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/


    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :first_name, :length => { :in => 3..20 }
    validates :last_name, :length => { :in => 3..20 }
    validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
    
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
    validates :password, :confirmation => true #password_confirmation attr
    validates_length_of :password, :in => 6..20, :on => :create


    def encrypt_password
      if password.present?
        self.salt = BCrypt::Engine.generate_salt
        self.password= BCrypt::Engine.hash_secret(password, salt)
      end
    end
    
    def clear_password
      self.password = nil
    end

    def match_password(password="")
        password == BCrypt::Engine.hash_secret(password, salt)
    end

    def self.authenticate(username_or_email="", login_password="")
      user = User.find_by_username(username_or_email)
      
      if user && user.match_password(login_password)
        return user
      else
        return false
      end
    end  

    def match_password(login_password="")
      password == BCrypt::Engine.hash_secret(login_password, salt)
    end

    def send_password_reset
      generate_token(:password_reset_token)
      self.password_reset_sent_at = Time.zone.now
      save!
      UserMailer.password_reset(self).deliver
    end

    def generate_token(column)
      begin
        self[column] = SecureRandom.urlsafe_base64
      end while User.exists?(column => self[column])
    end
	
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  layout 'layouts/post'

  def index
    @categories = Category.all
  end

  def show
    @cat = Category.find(params[:id])
    @posts = @cat.posts.limit(10).paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit( :name, :status )
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def tag_links(tags)
	  tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ") 
	end
	
	def tag_cloud(tags, classes)
	  max = tags.sort_by(&:count).last
	  tags.each do |tag|
	    index = tag.count.to_f / max.count * (classes.size-1)
	    yield(tag, classes[index.round])
	  end
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
    	session[:user_id] = user.id
  	end

	# Returns the current logged-in user (if any).
	def current_user
	    @current_user ||= User.find_by(id: session[:user_id])
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <p><label>Name </label><%= f.text_field :name %></p>
    <p><label>Show category <%= f.check_box :status %></label></p>

    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= form_for (@category), :html => { :multipart => true } do |f| %>
	<p><label>Name </label><%= f.text_field :name %></p>
	<p>
		<label>Show category </label> 
		<%= f.check_box :status, @category.status == 1 ? {:checked => true} : {:checked => false} %>
	</p>
	<p><%= f.submit 'Edit' %></p>
<% end %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>
<div class="posts-index"> 
  <% @categories.each do |category| %>
    <h2>Category: <%= category.name %></h2>
    <% category.posts.each do |post| %>
      <div class="col-md-3 post-detail">
        <%= image_tag post.image.url %>
        <h3><%= link_to post.name.first(30), post %></h3>
        <p><label>By </label> <%= link_to post.user.username, user_path(post.user.id) %></p>
        <p><label>Pushlished at </label> <%= time_ago_in_words(post.created_at) %></p>

        <% if session[:user_name] == 'hklong' %>
          <%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    <% end %>
  <% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%= @category.name %></h3>
<div class="posts-index">
	<% @posts.each do |post| %>
	  <div class="col-md-4 post-detail">
	    <%= image_tag post.image.url %>
	    <h3><%= link_to post.name.first(30), post %></h3>
	    <p><label>By </label> <%= link_to post.user.username, user_path(post.user.id) %></p>
	    <p><label>Pushlished at </label> <%= time_ago_in_words(post.created_at) %></p>

	    <% if session[:user_name] == 'hklong' %>
	      <%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
	    <% end %>
	  </div>

	<% end %>
</div>