config/routes.rb
Rails.application.routes.draw do

  resources :group_categories
  resources :group_catgories
  get 'password_resets/new'

  get 'index/index'

  resources :testimonials
  resources :product_categories
  get 'about' => 'pages#about'

  get 'contact' => 'pages#contact'

  get '/home-demo-2' => 'index#home2'
  get '/home-demo-3' => 'index#home3'

  #get 'pages/404'

  get 'login', to: 'sessions#new', as: 'login'

  resources :categories

  resources :sessions

  get '/login' => 'sessions#new'

  resources :users

  resources :password_resets

  get '/register' => 'users#new'

  get 'register/confirm/:id' => 'users#show'

  resources :posts do
    resources :comments
  end

  get '/blog' => 'posts#index'

  get 'tags/:tag', to: 'posts#tag', as: :tag

  resources :products do
    resources :reviews
  end

  get '/shop' => 'products#index'

  root "index#index"

  mount Ckeditor::Engine => '/ckeditor'

  # error pages
  #get "*any", to: "errors#not_found", :via => all
  #match "/500", :to => "errors#internal_server_error", :via => :all

  namespace :qsadmin do

    resources :posts

    resources :dashboards

    get '', to: 'dashboards#index', as: '/'
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :product_category
	has_many :reviews
	belongs_to :users
	has_attached_file :product_image
	validates_attachment_content_type :product_image, content_type: /\Aimage\/.*\Z/

	def self.search(search)
	  if search
	    where("name like ?", "%#{search}%") 
	  else
	    all
	  end
	end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  layout 'layouts/product', only: [:show]
  layout 'layouts/shop', only: [:index]

  def index
    @products = Product.all
    if params[:search]
      @products = Product.search(params[:search]).order("created_at DESC")
    else
      @products = Product.all.order('created_at DESC')
    end
  end

  def show
    @categories = ProductCategory.all.map{ |c| [c.name, c.id] }
    #@category = ProductCategory.find(params[:id])
    #@recent_posts = @category.products
    if @product.reviews.blank?
      @average_review = 0
    else
      @average_review = @product.reviews.average(:rating).round(2)
    end
  end

  def new
    @product = Product.new
    @categories = ProductCategory.all.map{ |c| [c.name, c.id] }
  end

  def create
    @product = Product.new(product_params)
    @product.product_category_id = params[:product_category_id]

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @categories = ProductCategory.all.map{ |c| [c.name, c.id] }
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :product_image, :detail, :price, :quantum, :note, :product_category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product, :html => { :multipart => true } do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <p><%= select_tag(:product_category_id, options_for_select(@categories), :prompt => "Select a category") %></p>
    <p><label>Name</label><%= f.text_field :name %></p>
    <p><label>Thumbnail</label><%= f.file_field :product_image %></p>
    <p><label>Details</label><%= f.cktext_area :detail %></p>
    <p><label>Prices</label><%= f.text_field :price %></p>
    <p><label>Quantums</label><%= f.text_field :quantum %></p>
    <p><label>Note</label><%= f.cktext_area :note %></p>
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= form_for @product, :html => { :multipart => true } do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <p><%= f.select :product_category_id, @categories %></p>
    <p><label>Name</label><%= f.text_field :name %></p>
    <p><label>Thumbnail</label><%= f.file_field :product_image %></p>
    <p><label>Details</label><%= f.cktext_area :detail %></p>
    <p><label>Prices</label><%= f.text_field :price %></p>
    <p><label>Quantums</label><%= f.text_field :quantum %></p>
    <p><label>Note</label><%= f.cktext_area :note %></p>
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<% if params[:search] %>
  Search : <%= params[:search] %>
<% end %>
<% if @products.blank? %>
  <h4>There are no products containing the term <%= params[:search] %>.</h4>
<% end %>

<div class="posts-index">

  <% if session[:user_name] == 'hklong' %>
      <p class="post-button clearfix">
          <%= link_to 'New Product', new_product_path %>
      </p>
  <% end %>

  <% if @products.count != 0 %>
    <% @products.limit(6).each do |product| %>

      <div class="col-md-3 post-index-detail">
        <div class="post-index-details">
          <%= image_tag product.product_image.url, :class => 'image' %>
          <div class="post-index-content">
            <h3><%= link_to product.name, product %></h3>
            <div class="average-review-rating" data-score=<%= product.reviews.average(:rating) %>>
            </div>

            <% if session[:user_name] == 'hklong' %>
              <%= link_to 'Destroy', product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
        </div>

      </div>

    <% end %>

  <% else %>
    <h4>Product is empty</h4>
  <% end %>

  <div class="clearfix"></div>

</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-4 product-image">
	<%= image_tag @product.product_image.url %>
</div>
<div class="col-md-8 product-detail">
	<h3><%= @product.name %></h3>
	<h2 class="avg-rating">Average Rating</h2>
	<div class="average-review-rating" data-score=<%= @average_review %>></div>
	<span>Category: <%= link_to @product.product_category.name, product_category_path(@product.product_category.id) %></span>
	<p><%= raw @product.detail %></p>
</div>

<div class="col-md-12 ">
	<ul class="tabs">
		<li class="li-active"><a href="#reviews" class="active">Reviews</a></li>
		<li><a href="#descriptions">Descriptions</a></li>
	</ul>
	<div id="reviews" class="tab-content" >
		<h1><%= @product.reviews.count %> Reviews</h1>
		<%= render @product.reviews %>

		<div>
			<% if session[:user_id] %>
				<%= link_to "Add Review", new_product_review_path(@product), class: "btn-custom register"  %>
			<% end %>
		</div>
	</div>

	<div id="descriptions" class="tab-content" >
		<p><%= raw @product.detail %></p>
	</div>

</div>	
<% if session[:user_id] && session[:user_name] == 'hklong' %>
	<%= link_to 'Edit', edit_product_path(@product) %>
<% end %>

<div class="col-md-12 related-posts">
	<h3>Recent Products</h3>
	<% Product.all.where(:product_category_id => @product.product_category.id).where.not(:id => @product.id ).limit(4).order('created_at DESC').each do |f| %>
		<div class="col-md-3 related-posts-details">
			<%= image_tag f.product_image.url %>
			<h3><%= link_to f.name, f %></h3>
			<p><label>Category: </label> <%= f.product_category.name %></p>
			<div class="average-review-rating" data-score=<%= @average_review %>></div>

		</div>
		
	<% end %>
</div>

<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>


<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>